// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });


import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // Tells Prisma to use the standard rust engine
  engine: "classic",
  
  datasource: {
    // Uses Prisma's built-in env helper instead of process.env
    url: env("DATABASE_URL")
  }
});